apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-services
spec:
  selector:
    matchLabels:
      app: micro-services
  template:
    metadata:
      labels:
        app: micro-services
    spec:
      containers:
        - name: micro-a
          image: michalkaszubowski/node-micro-a:latest
          ports:
            - containerPort: 3000
        - name: micro-b
          image: michalkaszubowski/node-micro-b:2.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
        - name: db
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
