apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-services
spec:
  selector:
    matchLabels:
      app: micro-services
  template:
    metadata:
      labels:
        app: micro-services
    spec:
      containers:
        - name: mongo-a
          image: mongo:latest
          command: ["sh"]
        - name: mongo-b
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
